[config]
default_to_workspace = false
load_cargo_aliases = true

[tasks.default]
alias = "build"

[tasks.watch]
script = "cargo watch -x clippy -x 'fmt --all' -x 'make nextest'"

[tasks.nextest]
command = "cargo"
args = ["nextest", "--no-tests", "pass"]

[tasks.fmt]
command = "cargo"
args = ["fmt", "--all"]

[tasks.dev]
run_task = { name = ["watch", "serve"], parallel = true }

[tasks.serve]
command = "cargo"
args = ["tauri", "dev"]
dependencies = ["pnpm"]

[tasks.precommit]
dependencies = ["clippy", "fmt", "pnpm"]

[tasks.pnpm]
command = "pnpm"
args = ["i"]

[tasks.build]
condition = { files_modified = { input = [
  "./Cargo.*",
  "./**/*.rs",
], output = [
  "./target/release/task-stack",
] } }
command = "cargo"
args = ["tauri", "build"]
dependencies = ["clippy", "fmt", "nextest", "pnpm"]
