[alias]
add = ["bin", "cargo-add"]
make = ["bin", "cargo-make"]
nextest = ["bin", "cargo-nextest"]
remove = ["bin", "cargo-rm"]
tauri = ["bin", "cargo-tauri"]
udeps = ["bin", "cargo-udeps"]
upgrade-local = ["bin", "cargo-upgrade"]
watch = ["bin", "cargo-watch"]
