name: Perform Tests

on:
  pull_request:
    branches:
      - main
jobs:
  Build-Tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, ubuntu-24.04-arm, windows-latest]
    runs-on: ${{ matrix.platform }}
    env:
      BINSTALL_NO_DISCOVER_GITHUB_TOKEN: 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.0.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          standalone: true
          run_install: false

      - name: Install Deps
        run: pnpm i

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest' || matrix.platform == 'ubuntu-24.04-arm'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config xdg-utils curl git build-essential pkg-config libglib2.0-dev libgtk-3-dev libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev javascriptcoregtk-4.1 libsoup-3.0 webkit2gtk-4.1

      - name: install Rust Deps
        run: |
          cargo install cargo-binstall
          cargo binstall cargo-run-bin -y

      - name: Build
        run: cargo make build
